# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate IBD probabilities
#'
#' A long description
#'
#' @param poptype A character string indicating the type of population. One of
#' ....
#' @param locfile A character string indicating the .loc file for the
#' population. The file should be in Flapjack format.
#' @param mapfile A character string indicating the .map file for the
#' population. The file should be in Flapjack format.
#' @param evalposfile An optional character string indicating a tab separated
#' .txt file containing combinations of chromosomes and positions to which the
#' calculations should be limited.
#' @param evaldist An optional numerical value indicating the maximum
#' distance for in between marker evaluation positions.
#'
#' @return A data.frame with IBD probabilities.
#'
#' @export
calcIBD <- function(poptype, locfile, mapfile, evalposfile = NULL, evaldist = NULL) {
    .Call(`_statgenIBD_calcIBD`, poptype, locfile, mapfile, evalposfile, evaldist)
}

